# command: "hypercorn --workers 1 --bind 0.0.0.0:8000 src.wsgi:app"
# command: "hypercorn --workers 2 --log-level info --error-log ./log/ERROR_LOG.log --access-log ./log/ACCESS_LOG.log --bind localhost:8000 asgi:app"
# command: "hypercorn --workers 2 --log-level info --bind localhost:8000 asgi:app"
# command: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker asgi:app"

version: '3'

services:

  api-dev:
    container_name: api-dev
    build:
      context: backend
      dockerfile: dockerfiles/Dockerfile.dev
    ports:
      - "8010:8010"
    volumes:
      - ./backend/src:/usr/app/src
    command: bash -c "
      uvicorn asgi:app \
        --host 0.0.0.0 \
        --port 8010 \
        --reload"
    restart: "on-failure"
    env_file:
      - ./infra.secrets.toml
    environment:
      CHICKIE_MYENV: prod
      APP_VERSION: "dev"

  # client-angular-prod:
  #   build:
  #     context: frontend-angular
  #     dockerfile: dockerfiles/Dockerfile.prod
  #   volumes:
  #     - ./frontend-angular/:/usr/app/
  #   ports:
  #     - "4200:4200"
  #     - "80:80"

  client-angular-dev:
    build:
      context: frontend-angular
      dockerfile: dockerfiles/Dockerfile.dev
    volumes:
      - ./frontend-angular/:/usr/app/
    ports:
      - "4200:4200"

