FROM python:3.11    

RUN useradd -ms /bin/bash chickie

RUN pip install --upgrade pip && pip install --upgrade setuptools

WORKDIR /home/chickie/backend

USER chickie

COPY ./requirements/api.txt requirements/api.txt

RUN pip install --no-cache-dir -r ./requirements/api.txt

ENV PATH="/home/chickie/.local/bin:${PATH}"

COPY ./config/.secrets.toml ./config/.secrets.toml
COPY ./config/settings.toml ./config/settings.toml

COPY . .

ENV PYTHONUNBUFFERED 1
ENV PYTHONBREAKPOINT 0
ENV TERM xterm-256color

CMD [ "uvicorn", "asgi:app", "--reload", "--reload-dir", "src", "--host", "0.0.0.0" ]
