dev:
	clear
	poetry run pyside6-uic views/main.ui \
		-o views/main_ui.py

	poetry run pyside6-uic views/loginForm.ui \
		-o views/loginForm_ui.py

	poetry run python app.py

compile:
	poetry run pyside6-uic views/main.ui \
		-o views/main_ui.py

	poetry run pyside6-uic views/loginForm.ui \
		-o views/loginForm_ui.py