dev:
	clear
	# make compile
	poetry run python app.py

compile:

	poetry run pyside6-uic \
		   src/views/main.ui \
		-o src/views/main_ui.py


	poetry run pyside6-uic \
		   src/views/loginForm.ui \
		-o src/views/loginForm_ui.py
