# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QMainWindow, QMenu, QMenuBar,
    QSizePolicy, QStatusBar, QWidget)

class Ui_Chickie(object):
    def setupUi(self, Chickie):
        if not Chickie.objectName():
            Chickie.setObjectName(u"Chickie")
        Chickie.resize(800, 600)
        self.actionCategoria = QAction(Chickie)
        self.actionCategoria.setObjectName(u"actionCategoria")
        self.actionCategoria_2 = QAction(Chickie)
        self.actionCategoria_2.setObjectName(u"actionCategoria_2")
        self.actionEntregador = QAction(Chickie)
        self.actionEntregador.setObjectName(u"actionEntregador")
        self.actionFeedback = QAction(Chickie)
        self.actionFeedback.setObjectName(u"actionFeedback")
        self.actionFuncionario = QAction(Chickie)
        self.actionFuncionario.setObjectName(u"actionFuncionario")
        self.actionMetodoDePagamento = QAction(Chickie)
        self.actionMetodoDePagamento.setObjectName(u"actionMetodoDePagamento")
        self.actionZona_de_entrega = QAction(Chickie)
        self.actionZona_de_entrega.setObjectName(u"actionZona_de_entrega")
        self.actionCliente = QAction(Chickie)
        self.actionCliente.setObjectName(u"actionCliente")
        self.actionPedido = QAction(Chickie)
        self.actionPedido.setObjectName(u"actionPedido")
        self.actionPreco = QAction(Chickie)
        self.actionPreco.setObjectName(u"actionPreco")
        self.actionPedido_2 = QAction(Chickie)
        self.actionPedido_2.setObjectName(u"actionPedido_2")
        self.actionPreco_2 = QAction(Chickie)
        self.actionPreco_2.setObjectName(u"actionPreco_2")
        self.actionProduto = QAction(Chickie)
        self.actionProduto.setObjectName(u"actionProduto")
        self.actionCategoria_3 = QAction(Chickie)
        self.actionCategoria_3.setObjectName(u"actionCategoria_3")
        self.actionEntregador_2 = QAction(Chickie)
        self.actionEntregador_2.setObjectName(u"actionEntregador_2")
        self.actionFeedback_2 = QAction(Chickie)
        self.actionFeedback_2.setObjectName(u"actionFeedback_2")
        self.actionFuncionario_2 = QAction(Chickie)
        self.actionFuncionario_2.setObjectName(u"actionFuncionario_2")
        self.actionZona_de_Entrega = QAction(Chickie)
        self.actionZona_de_Entrega.setObjectName(u"actionZona_de_Entrega")
        self.actionCliente_2 = QAction(Chickie)
        self.actionCliente_2.setObjectName(u"actionCliente_2")
        self.actionPre_o = QAction(Chickie)
        self.actionPre_o.setObjectName(u"actionPre_o")
        self.actionPedido_3 = QAction(Chickie)
        self.actionPedido_3.setObjectName(u"actionPedido_3")
        self.actionPreco_3 = QAction(Chickie)
        self.actionPreco_3.setObjectName(u"actionPreco_3")
        self.actionProduto_2 = QAction(Chickie)
        self.actionProduto_2.setObjectName(u"actionProduto_2")
        self.actionEntregador_3 = QAction(Chickie)
        self.actionEntregador_3.setObjectName(u"actionEntregador_3")
        self.actionFuncionario_3 = QAction(Chickie)
        self.actionFuncionario_3.setObjectName(u"actionFuncionario_3")
        self.actionMetodoDePagamento_2 = QAction(Chickie)
        self.actionMetodoDePagamento_2.setObjectName(u"actionMetodoDePagamento_2")
        self.actionCategoria_4 = QAction(Chickie)
        self.actionCategoria_4.setObjectName(u"actionCategoria_4")
        self.actionZona_de_entrega_2 = QAction(Chickie)
        self.actionZona_de_entrega_2.setObjectName(u"actionZona_de_entrega_2")
        self.actionHistorico = QAction(Chickie)
        self.actionHistorico.setObjectName(u"actionHistorico")
        self.actionObter_ajuda = QAction(Chickie)
        self.actionObter_ajuda.setObjectName(u"actionObter_ajuda")
        self.actionCompartilhar_ideias_e_comentarios = QAction(Chickie)
        self.actionCompartilhar_ideias_e_comentarios.setObjectName(u"actionCompartilhar_ideias_e_comentarios")
        self.actionSobre_o_Chickie = QAction(Chickie)
        self.actionSobre_o_Chickie.setObjectName(u"actionSobre_o_Chickie")
        self.centralwidget = QWidget(Chickie)
        self.centralwidget.setObjectName(u"centralwidget")
        Chickie.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(Chickie)
        self.statusbar.setObjectName(u"statusbar")
        Chickie.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(Chickie)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 27))
        self.menuNovo = QMenu(self.menubar)
        self.menuNovo.setObjectName(u"menuNovo")
        self.menuAtualizar = QMenu(self.menubar)
        self.menuAtualizar.setObjectName(u"menuAtualizar")
        self.menuRemover = QMenu(self.menubar)
        self.menuRemover.setObjectName(u"menuRemover")
        self.menuHistorico = QMenu(self.menubar)
        self.menuHistorico.setObjectName(u"menuHistorico")
        self.menuSobre = QMenu(self.menubar)
        self.menuSobre.setObjectName(u"menuSobre")
        Chickie.setMenuBar(self.menubar)

        self.menubar.addAction(self.menuNovo.menuAction())
        self.menubar.addAction(self.menuAtualizar.menuAction())
        self.menubar.addAction(self.menuRemover.menuAction())
        self.menubar.addAction(self.menuHistorico.menuAction())
        self.menubar.addAction(self.menuSobre.menuAction())
        self.menuNovo.addAction(self.actionCategoria_2)
        self.menuNovo.addAction(self.actionEntregador)
        self.menuNovo.addAction(self.actionFuncionario)
        self.menuNovo.addAction(self.actionMetodoDePagamento)
        self.menuNovo.addAction(self.actionZona_de_entrega)
        self.menuNovo.addAction(self.actionCliente)
        self.menuNovo.addAction(self.actionPreco)
        self.menuNovo.addAction(self.actionPedido_2)
        self.menuAtualizar.addAction(self.actionCategoria_3)
        self.menuAtualizar.addAction(self.actionEntregador_2)
        self.menuAtualizar.addAction(self.actionFeedback_2)
        self.menuAtualizar.addAction(self.actionFuncionario_2)
        self.menuAtualizar.addAction(self.actionZona_de_Entrega)
        self.menuAtualizar.addAction(self.actionPre_o)
        self.menuAtualizar.addAction(self.actionPedido_3)
        self.menuRemover.addAction(self.actionCategoria_4)
        self.menuRemover.addAction(self.actionEntregador_3)
        self.menuRemover.addAction(self.actionFuncionario_3)
        self.menuRemover.addAction(self.actionMetodoDePagamento_2)
        self.menuRemover.addAction(self.actionZona_de_entrega_2)
        self.menuRemover.addAction(self.actionPreco_3)
        self.menuRemover.addAction(self.actionProduto_2)
        self.menuHistorico.addAction(self.actionHistorico)
        self.menuSobre.addAction(self.actionObter_ajuda)
        self.menuSobre.addAction(self.actionCompartilhar_ideias_e_comentarios)
        self.menuSobre.addSeparator()
        self.menuSobre.addAction(self.actionSobre_o_Chickie)

        self.retranslateUi(Chickie)

        QMetaObject.connectSlotsByName(Chickie)
    # setupUi

    def retranslateUi(self, Chickie):
        Chickie.setWindowTitle(QCoreApplication.translate("Chickie", u"Chickie", None))
        self.actionCategoria.setText(QCoreApplication.translate("Chickie", u"Categoria", None))
        self.actionCategoria_2.setText(QCoreApplication.translate("Chickie", u"Categoria", None))
        self.actionEntregador.setText(QCoreApplication.translate("Chickie", u"Entregador", None))
        self.actionFeedback.setText(QCoreApplication.translate("Chickie", u"Feedback", None))
        self.actionFuncionario.setText(QCoreApplication.translate("Chickie", u"Funcion\u00e1rio", None))
        self.actionMetodoDePagamento.setText(QCoreApplication.translate("Chickie", u"M\u00e9todo de pagamento", None))
        self.actionZona_de_entrega.setText(QCoreApplication.translate("Chickie", u"Zona de entrega", None))
        self.actionCliente.setText(QCoreApplication.translate("Chickie", u"Cliente", None))
        self.actionPedido.setText(QCoreApplication.translate("Chickie", u"Pedido", None))
        self.actionPreco.setText(QCoreApplication.translate("Chickie", u"Pre\u00e7o", None))
        self.actionPedido_2.setText(QCoreApplication.translate("Chickie", u"Pedido", None))
        self.actionPreco_2.setText(QCoreApplication.translate("Chickie", u"Pre\u00e7o", None))
        self.actionProduto.setText(QCoreApplication.translate("Chickie", u"Produto", None))
        self.actionCategoria_3.setText(QCoreApplication.translate("Chickie", u"Categoria", None))
        self.actionEntregador_2.setText(QCoreApplication.translate("Chickie", u"Entregador", None))
        self.actionFeedback_2.setText(QCoreApplication.translate("Chickie", u"Feedback", None))
        self.actionFuncionario_2.setText(QCoreApplication.translate("Chickie", u"Funcion\u00e1rio", None))
        self.actionZona_de_Entrega.setText(QCoreApplication.translate("Chickie", u"Zona de Entrega", None))
        self.actionCliente_2.setText(QCoreApplication.translate("Chickie", u"Cliente", None))
        self.actionPre_o.setText(QCoreApplication.translate("Chickie", u"Pre\u00e7o", None))
        self.actionPedido_3.setText(QCoreApplication.translate("Chickie", u"Pedido", None))
        self.actionPreco_3.setText(QCoreApplication.translate("Chickie", u"Pre\u00e7o", None))
        self.actionProduto_2.setText(QCoreApplication.translate("Chickie", u"Produto", None))
        self.actionEntregador_3.setText(QCoreApplication.translate("Chickie", u"Entregador", None))
        self.actionFuncionario_3.setText(QCoreApplication.translate("Chickie", u"Funcion\u00e1rio", None))
        self.actionMetodoDePagamento_2.setText(QCoreApplication.translate("Chickie", u"M\u00e9todo de pagamento", None))
        self.actionCategoria_4.setText(QCoreApplication.translate("Chickie", u"Categoria", None))
        self.actionZona_de_entrega_2.setText(QCoreApplication.translate("Chickie", u"Zona de entrega", None))
        self.actionHistorico.setText(QCoreApplication.translate("Chickie", u"Historico de vendas", None))
        self.actionObter_ajuda.setText(QCoreApplication.translate("Chickie", u"Obter ajuda", None))
        self.actionCompartilhar_ideias_e_comentarios.setText(QCoreApplication.translate("Chickie", u"Compartilhar ideias e comentarios", None))
        self.actionSobre_o_Chickie.setText(QCoreApplication.translate("Chickie", u"Sobre o Chickie", None))
        self.menuNovo.setTitle(QCoreApplication.translate("Chickie", u"Novo", None))
        self.menuAtualizar.setTitle(QCoreApplication.translate("Chickie", u"Atualizar", None))
        self.menuRemover.setTitle(QCoreApplication.translate("Chickie", u"Remover", None))
        self.menuHistorico.setTitle(QCoreApplication.translate("Chickie", u"Hist\u00f3rico", None))
        self.menuSobre.setTitle(QCoreApplication.translate("Chickie", u"Sobre", None))
    # retranslateUi

