FROM node:18-alpine as build

WORKDIR /app

COPY package.json .

RUN npm install

COPY src src
COPY angular.json angular.json
COPY package-lock.json package-lock.json
COPY tsconfig.app.json tsconfig.app.json
COPY tsconfig.json tsconfig.json
COPY tsconfig.spec.json tsconfig.spec.json

RUN npm run build

FROM nginx:latest

COPY --from=build /app/dist/frontend-angular/browser /usr/share/nginx/html

COPY ./nginx/chickie.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
