FROM node:18-alpine as build

WORKDIR /usr/app

COPY package.json .

RUN npm install

RUN npm install -g @angular/cli@17

COPY src src
COPY angular.json angular.json
COPY package-lock.json package-lock.json
COPY tsconfig.app.json tsconfig.app.json
COPY tsconfig.json tsconfig.json
COPY tsconfig.spec.json tsconfig.spec.json

EXPOSE 4200

CMD ["ng", "serve", "--host", "0.0.0.0"]
