"""Ingredientes

Revision ID: 0f6a541d514f
Revises: c6c021195658
Create Date: 2024-01-29 22:07:02.189782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f6a541d514f'
down_revision: Union[str, None] = 'c6c021195658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredientes',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('produto_uuid', sa.String(length=36), nullable=False),
    sa.Column('loja_uuid', sa.String(length=36), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['loja_uuid'], ['lojas.uuid'], ),
    sa.ForeignKeyConstraint(['produto_uuid'], ['produtos.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredientes')
    # ### end Alembic commands ###
