"""ItemPedido.produto_nome,produto_desc

Revision ID: 13d5ba0e66ea
Revises: 49666cd4c8c1
Create Date: 2024-01-07 14:56:18.220620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13d5ba0e66ea'
down_revision: Union[str, None] = '49666cd4c8c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itens_pedido', sa.Column('produto_nome', sa.Text(), nullable=True))
    op.add_column('itens_pedido', sa.Column('produto_descricao', sa.Text(), nullable=True))
    op.drop_constraint('itens_pedido_produto_uuid_fkey', 'itens_pedido', type_='foreignkey')
    op.drop_column('itens_pedido', 'produto_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itens_pedido', sa.Column('produto_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.create_foreign_key('itens_pedido_produto_uuid_fkey', 'itens_pedido', 'produtos', ['produto_uuid'], ['uuid'])
    op.drop_column('itens_pedido', 'produto_descricao')
    op.drop_column('itens_pedido', 'produto_nome')
    # ### end Alembic commands ###
