"""Pedido table

Revision ID: 27e0cc575d2e
Revises: f1f180aba84c
Create Date: 2023-12-30 16:55:45.513141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27e0cc575d2e'
down_revision: Union[str, None] = 'f1f180aba84c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'categorias_de_produtos', ['uuid'])
    op.create_unique_constraint(None, 'enderecos', ['uuid'])
    op.add_column('entregadores', sa.Column('email', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'entregadores', ['uuid'])
    op.create_unique_constraint(None, 'feedbacks', ['uuid'])
    op.create_unique_constraint(None, 'funcionarios', ['uuid'])
    op.create_unique_constraint(None, 'itens_pedido', ['uuid'])
    op.create_unique_constraint(None, 'lojas', ['uuid'])
    op.add_column('pagamentos', sa.Column('metodo_pagamento_uuid', sa.String(length=36), nullable=False))
    op.create_unique_constraint(None, 'pagamentos', ['uuid'])
    op.drop_constraint('pagamentos_metodo_pagamento_fkey', 'pagamentos', type_='foreignkey')
    op.create_foreign_key(None, 'pagamentos', 'metodos_pagamento', ['metodo_pagamento_uuid'], ['uuid'])
    op.drop_column('pagamentos', 'metodo_pagamento')
    op.alter_column('pedidos', 'status_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_unique_constraint(None, 'pedidos', ['uuid'])
    op.create_unique_constraint(None, 'precos', ['uuid'])
    op.create_unique_constraint(None, 'produtos', ['uuid'])
    op.create_unique_constraint(None, 'status', ['uuid'])
    op.create_unique_constraint(None, 'zonas_de_entrega', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'zonas_de_entrega', type_='unique')
    op.drop_constraint(None, 'status', type_='unique')
    op.drop_constraint(None, 'produtos', type_='unique')
    op.drop_constraint(None, 'precos', type_='unique')
    op.drop_constraint(None, 'pedidos', type_='unique')
    op.alter_column('pedidos', 'status_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.add_column('pagamentos', sa.Column('metodo_pagamento', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pagamentos', type_='foreignkey')
    op.create_foreign_key('pagamentos_metodo_pagamento_fkey', 'pagamentos', 'metodos_pagamento', ['metodo_pagamento'], ['uuid'])
    op.drop_constraint(None, 'pagamentos', type_='unique')
    op.drop_column('pagamentos', 'metodo_pagamento_uuid')
    op.drop_constraint(None, 'lojas', type_='unique')
    op.drop_constraint(None, 'itens_pedido', type_='unique')
    op.drop_constraint(None, 'funcionarios', type_='unique')
    op.drop_constraint(None, 'feedbacks', type_='unique')
    op.drop_constraint(None, 'entregadores', type_='unique')
    op.drop_column('entregadores', 'email')
    op.drop_constraint(None, 'enderecos', type_='unique')
    op.drop_constraint(None, 'categorias_de_produtos', type_='unique')
    # ### end Alembic commands ###
