"""Pedido.celular

Revision ID: 33202267e4dd
Revises: 27e0cc575d2e
Create Date: 2023-12-30 17:37:57.273316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33202267e4dd'
down_revision: Union[str, None] = '27e0cc575d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('celular', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'celular')
    # ### end Alembic commands ###
