"""RmColEnd_Usuario_Loja

Revision ID: 75a89fb762a6
Revises: ab5de8565b6b
Create Date: 2024-01-02 02:26:25.712049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75a89fb762a6'
down_revision: Union[str, None] = 'ab5de8565b6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lojas_endereco_uuid_fkey', 'lojas', type_='foreignkey')
    op.drop_column('lojas', 'endereco_uuid')
    op.drop_constraint('usuarios_endereco_uuid_fkey', 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'endereco_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('endereco_uuid', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.create_foreign_key('usuarios_endereco_uuid_fkey', 'usuarios', 'enderecos', ['endereco_uuid'], ['uuid'])
    op.add_column('lojas', sa.Column('endereco_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.create_foreign_key('lojas_endereco_uuid_fkey', 'lojas', 'enderecos', ['endereco_uuid'], ['uuid'])
    # ### end Alembic commands ###
