"""EnderecosFKs

Revision ID: ab5de8565b6b
Revises: cde8a33a8bcf
Create Date: 2024-01-02 02:21:24.645140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab5de8565b6b'
down_revision: Union[str, None] = 'cde8a33a8bcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'avaliacoes_de_loja', ['uuid'])
    op.create_unique_constraint(None, 'avaliacoes_de_produtos', ['uuid'])
    op.create_unique_constraint(None, 'categorias_de_produtos', ['uuid'])
    op.create_unique_constraint(None, 'enderecos', ['uuid'])
    op.add_column('enderecos_entregas', sa.Column('pedido_uuid', sa.Text(), nullable=False))
    op.create_unique_constraint(None, 'enderecos_entregas', ['uuid'])
    op.create_foreign_key(None, 'enderecos_entregas', 'pedidos', ['pedido_uuid'], ['uuid'])
    op.add_column('enderecos_lojas', sa.Column('loja_uuid', sa.Text(), nullable=False))
    op.create_unique_constraint(None, 'enderecos_lojas', ['uuid'])
    op.create_foreign_key(None, 'enderecos_lojas', 'lojas', ['loja_uuid'], ['uuid'])
    op.add_column('enderecos_usuarios', sa.Column('usuario_uuid', sa.Text(), nullable=False))
    op.create_unique_constraint(None, 'enderecos_usuarios', ['uuid'])
    op.create_foreign_key(None, 'enderecos_usuarios', 'usuarios', ['usuario_uuid'], ['uuid'])
    op.create_unique_constraint(None, 'entregadores', ['uuid'])
    op.create_unique_constraint(None, 'funcionarios', ['uuid'])
    op.create_unique_constraint(None, 'itens_pedido', ['uuid'])
    op.create_unique_constraint(None, 'lojas', ['uuid'])
    op.create_unique_constraint(None, 'pagamentos', ['uuid'])
    op.create_unique_constraint(None, 'pedidos', ['uuid'])
    op.create_unique_constraint(None, 'precos', ['uuid'])
    op.create_unique_constraint(None, 'produtos', ['uuid'])
    op.create_unique_constraint(None, 'status', ['uuid'])
    op.create_unique_constraint(None, 'zonas_de_entrega', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'zonas_de_entrega', type_='unique')
    op.drop_constraint(None, 'status', type_='unique')
    op.drop_constraint(None, 'produtos', type_='unique')
    op.drop_constraint(None, 'precos', type_='unique')
    op.drop_constraint(None, 'pedidos', type_='unique')
    op.drop_constraint(None, 'pagamentos', type_='unique')
    op.drop_constraint(None, 'lojas', type_='unique')
    op.drop_constraint(None, 'itens_pedido', type_='unique')
    op.drop_constraint(None, 'funcionarios', type_='unique')
    op.drop_constraint(None, 'entregadores', type_='unique')
    op.drop_constraint(None, 'enderecos_usuarios', type_='foreignkey')
    op.drop_constraint(None, 'enderecos_usuarios', type_='unique')
    op.drop_column('enderecos_usuarios', 'usuario_uuid')
    op.drop_constraint(None, 'enderecos_lojas', type_='foreignkey')
    op.drop_constraint(None, 'enderecos_lojas', type_='unique')
    op.drop_column('enderecos_lojas', 'loja_uuid')
    op.drop_constraint(None, 'enderecos_entregas', type_='foreignkey')
    op.drop_constraint(None, 'enderecos_entregas', type_='unique')
    op.drop_column('enderecos_entregas', 'pedido_uuid')
    op.drop_constraint(None, 'enderecos', type_='unique')
    op.drop_constraint(None, 'categorias_de_produtos', type_='unique')
    op.drop_constraint(None, 'avaliacoes_de_produtos', type_='unique')
    op.drop_constraint(None, 'avaliacoes_de_loja', type_='unique')
    # ### end Alembic commands ###
