"""Pedido.comentarios

Revision ID: c6c021195658
Revises: 13d5ba0e66ea
Create Date: 2024-01-15 23:32:07.724352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6c021195658'
down_revision: Union[str, None] = '13d5ba0e66ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enderecos')
    op.add_column('pedidos', sa.Column('comentarios', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'comentarios')
    op.create_table('enderecos',
    sa.Column('uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('uf', postgresql.ENUM('AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO', name='uf'), autoincrement=False, nullable=True),
    sa.Column('cidade', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('logradouro', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('numero', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('complemento', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bairro', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('cep', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('time_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('time_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uuid', name='enderecos_pkey'),
    sa.UniqueConstraint('uuid', name='enderecos_uuid_key')
    )
    # ### end Alembic commands ###
